
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex
    username: bootuser
    password: Bootuser12!@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

#JWT
application:
  jwt:
    secretKey:
      b9601b0e91f9b639d06446765096744b809df8ff1095520bc71be5c1310206c0
    expiration: 900000 #15분
    refreshExpiration: 86400000 #1일
